### ISSUE TITLE
Proposal: make circe overridable in Resources by extending from trait

### ISSUE THREAD

**Issue by rbrondgeest** [guardrail-dev/guardrail#1024]
For being able to override the default behavior of Circe I would like to move CirceInstance members to its trait extension in in generated Resources.

Example:

`class LabelResource[F[_]](mapRoute: (String, Request[F], F[Response[F]]) => F[Response[F]] = (_: String, _: Request[F], r: F[Response[F]]) => r)(implicit F: Async[F]) extends Http4sDsl[F] **with CirceInstances**`

This would allow for overriding f.e. default error handler behavior like so:

```
val apiResoure = new MyGeneratedApiResource[Task] with CirceInstances {
      override def jsonDecodeError: (Json, NonEmptyList[DecodingFailure]) => DecodeFailure = {
        (json, failures) => MyCustomMoreDescriptiveError(failures)
      }
}

```

If this is ok, please let me know, I am willing to issue a pull request.

**Comment by rbrondgeest** [comment]
I'll just propose by PR

**Comment by blast-hardcheese** [comment]
This makes sense, though namespace collisions with user-controlled methods in handlers is not ideal.

This would better be served by configurations passed to `routes`, since that's the part of the code that actually does the work (think of the handler as purely business logic, almost a configuration in itself, that gets passed to the resource)
